---
- project:
    name: OP2
    logo: images/op2.png
    url: https://github.com/RetiFier/op2
  name: ONE PAGE PROTOTYPE (OP2)
  date: Sep 2020
  technologies:
    - React
    - Electron
    - Java Script
    - CSS
  description: A prototyping multiplatform application (windows/mac/linux) built using JS and its relevant frameworks and libarries. Made with the purpose of creating single webpages in a matter of minutes, one can expect codes to be generated after customising at their choice. with the functionality include the ability to import and export codes
- project:
    name: SE2020
    logo:
    url: https://github.com/aungkoman/se2020
  name: SE 2020
  date: Nov 2020
  technologies:
    - React
    - Styled Component
    - Redux
  description: award-winning manage-product website alongside two other team members under the title of SSDLC (Secure Software Development Life Cycle). I contributed this project as a front-end developer, utilizing React and Redux.
