---
- project:
    name: Reti Blog
    logo:
    url: https://github.com/RetiFier/superbase-blog
  name: Reti Blog
  date: Dec 2024
  technologies:
    - Next.js 14
    - Supabase
    - Tailwind CSS
    - shadcn/ui
  description: 
    A modern blogging platform built with Next.js 14, Supabase, and Tailwind CSS. 
    Features include a rich text editor, categories, tags, view analytics, and a comments system. 
    Supports dark/light themes, user roles, and profile management with responsive design.

- project:
    name: SeedSafer
    logo:
    url: https://github.com/RetiFier/seedsafer
  name: SeedSafer - A Mobile App for Secure Seed Storage
  date: Mar 2023
  technologies:
    - React Native
    - TypeScript
    - Ethereum API
    - Web3.js
  description: 
    A React Native and TypeScript mobile app designed to securely store twelve-word recovery seeds, derive private keys, and display ETH balances and addresses. 
    Focused on blockchain integration and private key management with secure, user-friendly interfaces.

- project:
    name: OP2
    logo: images/op2.png
    url: https://github.com/RetiFier/op2
  name: ONE PAGE PROTOTYPE (OP2)
  date: Sep 2020
  technologies:
    - React
    - Electron
    - JavaScript
    - CSS
  description: 
    A prototyping multiplatform application (Windows/Mac/Linux) built using JavaScript and relevant frameworks. 
    Designed to create single webpages quickly, generating code based on user customization. 
    Includes import/export functionality for code.

- project:
    name: SE2020
    logo:
    url: https://github.com/aungkoman/se2020
  name: SE 2020
  date: Nov 2020
  technologies:
    - React
    - Styled Components
    - Redux
  description: 
    Award-winning product management website developed with a team under SSDLC (Secure Software Development Life Cycle). 
    Contributed as a front-end developer using React and Redux.

- project:
    name: Portfolio
    logo:
    url: https://github.com/RetiFier/my-portfolio
  name: Portfolio Website for Developer
  date: Mar 2022
  technologies:
    - React
    - Gatsby
    - Tailwind CSS
    - TypeScript
    - YAML
  description: 
    An open-source developer portfolio template built with Gatsby and Tailwind CSS.

- project:
    name: Pet Sitter
    logo:
    url: https://github.com/hatchways/team-cedar
  name: A website that helps dog owners find dog sitters
  date: Mar 2022
  technologies:
    - React
    - Node.js
    - Express JS
    - TypeScript
    - MongoDB
  description: 
    Collaborated on a platform to help dog owners find pet sitters. 
    Worked as a full-stack developer, gaining valuable experience from both technical contributions and mentorship from the team lead.
